### ISSUE TITLE
potential copyright issue from dependency "wordwrap"

### ISSUE THREAD

**Issue by ralf0131** [gkz/optionator#31]
[wordwrap](https://github.com/substack/node-wordwrap) publishes its test directory in which a text file 'idleness.txt' is included. This may introduce potential copyright issue.

see more from substack/node-wordwrap#21

**Comment by nzakas** [comment]
This is an issue of concern for ESLint, as well:
https://github.com/eslint/eslint/issues/11536

I'm not sure if there's another package available to switch to, but if so, it would be helpful to do so.

**Comment by gkz** [comment]
Thanks for letting me know, I'll look into fixing this

**Comment by gkz** [comment]
Closed with https://github.com/gkz/optionator/commit/bf4b1da28ba085646e0ae9bae602542176f8e635
