### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) on dependency 'word-wrap'

### ISSUE THREAD

**Issue by Globant-Eduardo-Cerda** [gkz/optionator#44]
Based on this [post](https://github.com/jonschlinkert/word-wrap/issues/32)

Software like snyk / DependencyTrack are yielding a ReDoS on the word-wrap package. This affects you because of the direct dependency on your project.

**Comment by icbat** [comment]
[Thread from word-wrap](https://github.com/jonschlinkert/word-wrap/pull/33) for reference. It's unclear when/if that's going to be fixed at the library level, at time of writing I haven't seen anything from the maintainer in that thread yet.

**Comment by SharpFu** [comment]
I have meet this issue.

**Comment by SharpFu** [comment]
@gkz , If you have free time ,pls help to fix this issue. thanks.

**Comment by gkz** [comment]
What issue did you actually encounter?
The author of the CLI tool using Optionator would need to purposefully make a bad description. It doesn't operate on user generated input. You could simply not use that CLI tool?
I understand the theoretical problem, and am happy to update to another package, but I'm just not understanding the actual issue in practice.

**Comment by icbat** [comment]
For me at least, I don't think there really is an actual technical issue. The problem I'm hitting is that some organizations treat all CVEs the same. My personal use-case is using eslint; which doesn't have a lot of surface area for a real ReDoS vector. However, it still flags the same as anything else, and I am still required to remediate (or file exceptions, etc.).

**Comment by gkz** [comment]
Does anyone have a suggestion for an alternate package? 

(I've already had to change the word wrap package once already, when the original one had licensing issues!)

**Comment by SharpFu** [comment]
I am used "eslint": "^7.14.0" and when I use snyk check my project. and then throw a error as the image
![image](https://user-images.githubusercontent.com/11939125/233911348-a4ef7233-e1cd-4bbb-bcf6-6916e41a7e20.png)

**Comment by gkz** [comment]
I mean an alternative for word-wrap

**Comment by rhuddleston** [comment]
wordwrapjs maybe?

**Comment by wellwelwel** [comment]
Hi @gkz.

For now, I think the @aashutoshrathi's `word-wrap` fork is a good alternative, because it's only changes a single fix focused on the vulnerability. In other words, it won't break anything.

You can comparing changes [here](https://github.com/jonschlinkert/word-wrap/compare/jonschlinkert:786ebf1...aashutoshrathi:87a3667) and see the @aashutoshrathi's [npm package](https://www.npmjs.com/package/@aashutoshrathi/word-wrap).

Regardless, I see this as a temporary measure.

**Comment by gkz** [comment]
I have published 0.9.2 that should resolve the issue. 

Thanks @wellwelwel for the tip.

**Comment by devpeerapong** [comment]
Did you publish the package to npm ?

**Comment by wellwelwel** [comment]
Hi @gkz, 

As before in my comment:
> Regardless, I see this as a temporary measure.

I would just like to say that the security issue has been solved in the original **word-wrap** project today 🙋🏻‍♂️

---

Related:
- https://github.com/jonschlinkert/word-wrap/pull/33
- https://github.com/jonschlinkert/word-wrap/pull/41
- https://github.com/jonschlinkert/word-wrap/issues/43
