### ISSUE TITLE
Regular Expression Denial of Service Vulnerability in Dependency

### ISSUE THREAD

**Issue by randompixel** [gkz/optionator#48]
Synk is reporting a vulnerability from this package as it depends on Word Wrap 1.2.3
```
eslint@8.33.0 › optionator@0.9.1 › word-wrap@1.2.3
```

The advisory for this issue is here https://github.com/advisories/GHSA-j8xg-fqg3-53r7 and it appears it was fixed in Word Wrap 1.2.4

Any chance you could update the dependencies and release a new version?

Thanks,

**Comment by 12beesinatrenchcoat** [comment]
Should have been fixed with https://github.com/gkz/optionator/pull/46 (switching to temporary fork with fix, see also https://github.com/jonschlinkert/word-wrap/pull/33).
word-wrap 1.2.4 does not (yet) exist.

**Comment by randompixel** [comment]
Great, thanks :)
