### ISSUE TITLE
[Security] Update `word-wrap` package

### ISSUE THREAD

**Issue by BimBoss** [gkz/optionator#52]
<img width="921" alt="image" src="https://github.com/gkz/optionator/assets/16728540/3b13b926-4531-4061-9235-320a9a4fa5d7">
<img width="461" alt="image" src="https://github.com/gkz/optionator/assets/16728540/115842d1-d981-44d7-a4da-256f8aae8bb1">

Please update the `word-wrap` package to the latest version. Thanks.

**Comment by tannerhuynh** [comment]
Bump. Tried to update Eslint newest version with Optionator but still getting word-wrap below 1.2.4. Latest version fix is 1.2.4.

**Comment by gkz** [comment]
Optionator 0.9.3 uses [@aashutoshrathi/word-wrap](https://www.npmjs.com/package/%40aashutoshrathi%2Fword-wrap), not `word-wrap`, and does not contain the security issue.

**Comment by gkz** [comment]
Closed with ae0692f84e081089e09ad962ab6fd55aacccce3c
